name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore NuGet
      run: dotnet restore

    - name: Build & Test
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          pwsh ./build.ps1
          pwsh ./test.ps1
        else
          chmod +x ./build.sh ./test.sh
          ./build.sh
          ./test.sh
        fi
